export const ticketTxt = {
  fr: {
    available_slots: "Horaires disponibles",
    loading: "Chargement...",
    no_slots: "Aucun horaire disponible",
    select_slot: "Sélectionnez un horaire",
    personal_infos: "Informations personnelles",
    first_name: "Prénom",
    last_name: "Nom",
    email: "Email",
    prices: "Tarifs",
    donation: "Soutenir le musée",
    proceed_to_payment: "Valider la réservation",
    warningEmail: "les billets seront envoyés vers l’adresse email que vous avez renseignée ici, vérifiez qu’il n’y a pas d’erreur et n’hésitez pas à vérifier dans les spams",
  },
  en: {
    available_slots: "Available hours",
    loading: "Loading...",
    no_slots: "No hours available",
    select_slot: "Select an hour",
    personal_infos: "Personal informations",
    first_name: "First name",
    last_name: "Last name",
    email: "Email",
    prices: "Prices",
    donation: "Support the museum",
    proceed_to_payment: "Validate the reservation",
    warningEmail: "the tickets will be sent to the email address you have entered here, please check that there is no error and do not hesitate to check in the spam",
  },
}