export const hudTxt = {
  fr: {
    left: '(Q / ←)',
    right: '(D / →)',
    jump: '(Espace / Up / Z)',
    action: '(E / F)',
    altLeft: 'Déplacer à gauche',
    altRight: 'Déplacer à droite',
    altJump: 'Sauter',
    altAction: 'Interagir',
    moveLeft: 'Déplacer à gauche',
    moveRight: 'Déplacer à droite',
    jumpAction: 'Sauter',
    interactAction: 'Interagir',
    keyboardKeys: 'Clavier',
    virtualPad: 'Pad virtuel',
    soundOn: 'Activer le son',
    soundOff: 'Couper le son',
  },
  en: {
    left: '(Q / ←)',
    right: '(D / →)',
    jump: '(Space / Up / Z)',
    action: '(E / F)',
    altLeft: 'Move left',
    altRight: 'Move right',
    altJump: 'Jump',
    altAction: 'Interact',
    moveLeft: 'Move left',
    moveRight: 'Move right',
    jumpAction: 'Jump',
    interactAction: 'Interact',
    keyboardKeys: 'Keyboard',
    virtualPad: 'Virtual pad',
    soundOn: 'Enable sound',
    soundOff: 'Mute sound',
  },
}

